/* empty css                      */import{S as u,i as f}from"./assets/vendor-9310f15c.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const n={form:document.querySelector(".search-form"),input:document.querySelector(".search-inp"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),searchBtn:document.querySelector(".search-btn")},d="https://pixabay.com/api/",m="41834264-e3d0e5d80121a8a176d918e74";n.form.addEventListener("submit",t=>{t.preventDefault();const s=n.form.query.value.trim(),a=`${d}?key=${m}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`;p(a).then(o=>{o.hits.length===0&&(h("Sorry, there are no images matching your search query. Please, try again!"),i(!1)),n.gallery.innerHTML=y(o.hits),i(!1),new u(".gallery-item a",{captionsData:"alt",captionDelay:250}),n.form.reset()}).catch(o=>console.error(o))});function p(t){return i(!0),fetch(t).then(s=>{if(!s.ok)throw new Error(s.ststusText);return s.json()})}function y(t){return t.map(({webformatURL:s,largeImageURL:a,tags:o,likes:e,views:r,comments:l,downloads:c})=>`
        <li class="gallery-item">
  <a class="gallery-link" href="${a}">
    <img
      class="gallery-image"
      src="${s}"
      alt="${o}"
    />
    <p class="gallery-descr">likes: <span class="descr-span">${e}</span> views: <span class="descr-span">${r}</span> comments: <span class="descr-span">${l}</span> downloads: <span class="descr-span">${c}</span></p>
  </a>
</li>`).join("")}function h(t){f.show({class:"error-svg",position:"topRight",icon:"error-svg",message:t,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}function i(t=!0){n.loader.style.display=t?"inline-block":"none",n.searchBtn.disabled=t}
//# sourceMappingURL=commonHelpers.js.map
